version: '3.6'

services:
  node1:
    image: mongo:4.2.8
    ports:
      - 6001:27017
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "if mongo --eval 'quit(db.runCommand({ replSetGetStatus: 1 }).ok ? 1 : 0)'; then exit 0; fi; exit 1;"]
      interval: 20s
      timeout: 5s
      retries: 5
      start_period: 40s
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0" ]

  node2:
    image: mongo:4.2.8
    ports:
      - 6002:27017
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "if mongo --eval 'quit(db.runCommand({ replSetGetStatus: 1 }).ok ? 1 : 0)'; then exit 0; fi; exit 1;"]
      interval: 20s
      timeout: 5s
      retries: 5
      start_period: 40s
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0" ]

  node3:
    image: mongo:4.2.8
    ports:
      - 6003:27017
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "if mongo --eval 'quit(db.runCommand({ replSetGetStatus: 1 }).ok ? 1 : 0)'; then exit 0; fi; exit 1;"]
      interval: 20s
      timeout: 5s
      retries: 5
      start_period: 40s
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0" ]

  mongosetup:
    image: mongo:4.2.8
    links:
      - node1:node1
      - node2:node2
      - node3:node3
    depends_on:
      - node1
      - node2
      - node3
    volumes:
      - ./scripts:/scripts
    restart: "no"
    entrypoint: [ "bash", "/scripts/mongo_setup.sh" ]
