version: "3.6"

services:
  node1:
    build: ./
    restart: unless-stopped
    ports:
      - "5001:3306"
    command: sudo -u mysql mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --wsrep-new-cluster
    healthcheck:
        test: mysqladmin ping 
        interval: 20s
        timeout: 5s
        retries: 5
        start_period: 40s

  node2:
    build: ./
    restart: unless-stopped
    ports:
      - "5002:3306"
    links:
      - node1
    command: sudo -u mysql mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    healthcheck:
        test: mysqladmin ping 
        interval: 20s
        timeout: 5s
        retries: 5
        start_period: 40s

  node3:
    build: ./
    restart: unless-stopped
    ports:
      - "5003:3306"
    links:
      - node1
    command: sudo -u mysql mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    healthcheck:
        test: mysqladmin ping 
        interval: 20s
        timeout: 5s
        retries: 5
        start_period: 40s